cognitive-complexity-threshold = 15

disallowed-names = [
    "bool",
    "char",
    "str",
    "f32",
    "f64",
    "i8",
    "i16",
    "i32",
    "i64",
    "u8",
    "u16",
    "u32",
    "u64",
    "isize",
    "usize",
    "String",
    "Vec",
    "vec",
    "HashMap",
    "HashSet",
    "BTreeMap",
    "BTreeSet",
    "RwLock",
    "Mutex",
    "Arc",
]
