[package]
name = "example_tcp_sofh_tokio_codec"
version = "0.1.0"
edition = "2021"

[dependencies]
fesofh = { path = "../../crates/fesofh", features = ["utils-tokio"] }
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"] }
