[package]
name = "example_json_encoding"
version = "0.1.0"
edition = "2018"

[dependencies]
fefix = { path = "../../crates/fefix", features = ["json-encoding", "fix42"] }
deadpool = "0.7"
tide = "0.16"
tokio = { version = "1", features = ["rt", "macros"] }