[package]
name = "example_coinbase_codegen"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[dependencies]
fefix = { path = "../../crates/fefix" }
rust_decimal = "1"

[build-dependencies]
fefix = { path = "../../crates/fefix", features = ["codegen"] }
