[package]
name = "example_encode_new_order_single"
version = "0.1.0"
edition = "2021"

[dependencies]
decimal = "2"
fefix = { path = "../../crates/fefix", features = ["fix44", "utils-decimal", "utils-rust-decimal"] }
rust_decimal = "1"
rust_decimal_macros = "1"
