[package]
name = "ferrumfix-quickfix-cpp-harness"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
fefix = { path = "../../../crates/fefix" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
tokio-util = { version = "0.7", features = ["compat"] }

[workspace]
